import { StyledTable, StyledTh, StyledTr, StyledTd } from "./styles"




function Table() {
  return (
    <>
      <StyledTable>
          <StyledTr>
            <StyledTh>Name</StyledTh>
            <StyledTh>Type</StyledTh>
            <StyledTh>HP</StyledTh>
            <StyledTh>Attack</StyledTh>
            <StyledTh>Defense</StyledTh>
            <StyledTh>Sp.Attack</StyledTh>
            <StyledTh>Sp.Defense</StyledTh>
            <StyledTh>Speed</StyledTh>
            <StyledTh>Total</StyledTh>
          </StyledTr>
          <StyledTr>
            <StyledTd>Blastoise</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
          </StyledTr>
          <StyledTr>
            <StyledTd>Bulbasaur</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
          </StyledTr>
          <StyledTr>
            <StyledTd>Caterpie</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
          </StyledTr>
          <StyledTr>
            <StyledTd>Charizard</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
          </StyledTr>
          <StyledTr>
            <StyledTd>Charmander</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
          </StyledTr>
          <StyledTr>
            <StyledTd>Charmeleon</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
          </StyledTr>
          <StyledTr>
            <StyledTd>Ivysaur</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
          </StyledTr>
          <StyledTr>
            <StyledTd>Squirtle</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
          </StyledTr>
          <StyledTr>
            <StyledTd>Venusaur</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
          </StyledTr>
          <StyledTr>
            <StyledTd>Wartortle</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
            <StyledTd>79</StyledTd>
          </StyledTr>
      </StyledTable> 
    </>
  )
}

export default Table
